[default]
    APPNAME = "Expense Overseer"
    VERSION = "0.2.0"

    DATABASE_PORT = "5432"
    DATABASE_USER = "postgres"
    DATABASE_PASSWORD = "postgres"
    DATABASE_DB = "expense_overseer"
    DATABASE_HOST = "localhost"
    DATABASE_ECHO_MODE = false

    TG_BOT_TOKEN = ""

[test]
    DATABASE_DB = "test-db"
    DATABASE_HOST = "postgres"
